# Generated by Django 6.0.3 on 2026-03-05 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('outros', 'Outros')], max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'categoria')},
            },
        ),
    ]
